[[ssh-keys]]
item = "Github - Personal"
vault = "Privado"

[[ssh-keys]]
item = "Github - ASAPP"
vault = "ASAPP"

[[ssh-keys]]
item = "GitLab - Asapp"
vault = "ASAPP"

[[ssh-keys]]
item = "Bitbucket"
vault = "Trick"
